[package]
name = "njord_derive"
version = "0.1.0"
edition = "2021"
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "Macros implementations."
license = "BSD-3-Clause"
documentation = "https://docs.rs/njord/latest/njord/"
repository = "https://github.com/mjovanc/njord"
readme = "crates-io.md"
rustc = "1.74.0"

[lib]
name = "njord_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0"
syn = "2.0.28"

[dev-dependencies]
njord = { version = "0.1.0", path = "../njord" }
