[book]
title = "Njord - A lightweight ORM library in Rust"
authors = ["Marcus Cvjeticanin"]
description = "A lightweight ORM library in Rust."
language = "en"
git-repository-url = "https://github.com/njord-rs/njord"
git-repository-icon = "fa-github"
copy-fonts = true
edit-url-template = "https://github.com/njord-rs/njord/tree/docs/src/{path}"
cname = "njord.rs"
input-404 = "not-found.md"

[build]
target-dir = "book"
